### ISSUE TITLE
unexpected behavior

### ISSUE THREAD

**Issue by Edo78** [jayli/vim-easydebugger#15]
I'm experiencing something wrong using this plugin.

I'm trying to keep it really simple with a vimrc like the one from your example
```
call plug#begin('~/.vim/plugged')
Plug 'jayli/vim-easydebugger'
call plug#end()

" Debugger startup
nmap <S-R>   <Plug>EasyDebuggerInspect
nmap <S-W>   <Plug>EasyDebuggerWebInspect
" pause
nmap <F7>    <Plug>EasyDebuggerPause
tmap <F7>    <Plug>EasyDebuggerPause
" stepinto
nmap <F8>    <Plug>EasyDebuggerStepIn
tmap <F8>    <Plug>EasyDebuggerStepIn
" stepout
nmap <S-F8>  <Plug>EasyDebuggerStepOut
tmap <S-F8>  <Plug>EasyDebuggerStepOut
" step by step
nmap <F9>    <Plug>EasyDebuggerNext
tmap <F9>    <Plug>EasyDebuggerNext
" Continue
nmap <F10>   <Plug>EasyDebuggerContinue
tmap <F10>   <Plug>EasyDebuggerContinue
" toggle line break points
nmap <F12>   <Plug>EasyDebuggerSetBreakPoint
```
then I wrote a simple js as
```
for(let i=0; i<10; i++){
        console.log(i);
        if(i === 5){
                console.log('yeah');
        }
}
```
then I press `shift+r` to open the debugger but if I try to write `next` (I have to give focus to the debugger split in order to do that) I got the following behavior
```
< Debugger listening on ws://127.0.0.1:9229/7aefaff9-82b9-42cd-bcd8-d0a0e9771148
< For help, see: https://nodejs.org/en/docs/inspector
< Debugger attached.
Break on start in file:///Users/edo/test/test.js:1
> 1 for(let i=0; i<10; i++){
  2     console.log(i);
  3     if(i === 5){
debug> kill
< Debugger listening on ws://127.0.0.1:9229/7aefaff9-82b9-42cd-bcd8-d0a0e9771148
< For help, see: https://nodejs.org/en/docs/inspector
debug> next
Thrown:
Error: Use `run` to start the app again.
    at Promise (internal/deps/node-inspect/lib/internal/inspect_client.js:238:16)
    at new Promise (<anonymous>)
    at Client.callMethod (internal/deps/node-inspect/lib/internal/inspect_client.js:236:12)
    at Proxy.callVirtualMethod (internal/deps/node-inspect/lib/_inspect.js:140:23)
    at Object.get next [as next] (internal/deps/node-inspect/lib/internal/inspect_repl.js:857:25)
debug> run
< Debugger listening on ws://127.0.0.1:9229/5fbea1d1-440b-4144-9284-0ee961da4e18
< For help, see: https://nodejs.org/en/docs/inspector
< Debugger attached.
Break on start in file:///Users/edo/test/test.js:1
> 1 for(let i=0; i<10; i++){
  2     console.log(i);
  3     if(i === 5){
debug> next
break in file:///Users/edo/test/test.js:1
> 1 for(let i=0; i<10; i++){
  2     console.log(i);
  3     if(i === 5){
debug>
```
If I try to set a breakpoint pressing `F12` I get another error
```
debug> setBreakpoint('test.js', 4);list(1)
Thrown:
internal/deps/node-inspect/lib/internal/inspect_repl.js:588
    return selectedFrame.list(delta)
                         ^

TypeError: Cannot read property 'list' of null
    at list (internal/deps/node-inspect/lib/internal/inspect_repl.js:588:26)
    at repl:1:29
    at Script.runInContext (vm.js:133:20)
    at Object.runInContext (vm.js:311:6)
    at REPLServer.controlEval (internal/deps/node-inspect/lib/internal/inspect_repl.js:521:25)
    at bound (domain.js:402:14)
    at REPLServer.runBound [as eval] (domain.js:415:12)
    at REPLServer.onLine (repl.js:642:10)
    at REPLServer.emit (events.js:198:13)
    at REPLServer.EventEmitter.emit (domain.js:448:20)
debug> (node:9493) UnhandledPromiseRejectionWarning: Error: Use `run` to start the app again.
    at Promise (internal/deps/node-inspect/lib/internal/inspect_client.js:238:16)
    at new Promise (<anonymous>)
    at Client.callMethod (internal/deps/node-inspect/lib/internal/inspect_client.js:236:12)
    at Proxy.callVirtualMethod (internal/deps/node-inspect/lib/_inspect.js:140:23)
    at setBreakpoint (internal/deps/node-inspect/lib/internal/inspect_repl.js:718:8)
    at repl:1:1
    at Script.runInContext (vm.js:133:20)
    at Object.runInContext (vm.js:311:6)
    at REPLServer.controlEval (internal/deps/node-inspect/lib/internal/inspect_repl.js:521:25)
    at bound (domain.js:402:14)
(node:9493) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9493) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
even the `repl` command gives me an error
```
debug> repl
Press Ctrl + C to leave debug repl
> i
Thrown:
Error: Use `run` to start the app again.                                                                                                                                                                    at Promise (internal/deps/node-inspect/lib/internal/inspect_client.js:238:16)
    at new Promise (<anonymous>)                                                                                                                                                                            at Client.callMethod (internal/deps/node-inspect/lib/internal/inspect_client.js:236:12)
    at Proxy.callVirtualMethod (internal/deps/node-inspect/lib/_inspect.js:140:23)
    at evalInCurrentContext (internal/deps/node-inspect/lib/internal/inspect_repl.js:505:20)
    at REPLServer.debugEval [as eval] (internal/deps/node-inspect/lib/internal/inspect_repl.js:541:22)
    at REPLServer.onLine (repl.js:642:10)
    at REPLServer.emit (events.js:198:13)
    at REPLServer.EventEmitter.emit (domain.js:448:20)
    at REPLServer.Interface._onLine (readline.js:308:10)
>
```
I'm working on a mac and this is my `vim --version`
```
VIM - Vi IMproved 8.1 (2018 May 18, compilato Jul  8 2019 19:24:38)
Versione macOS
Patch incluse: 1-1650
Compilato da Homebrew
Versione gigante senza GUI.  Funzionalità incluse (+) o escluse (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
-balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
-browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
-clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       -X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        -xsmp
+emacs_tags        -mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary
+extra_search      +mouse_sgr         -tag_old_static
   file vimrc di sistema: "$VIM/vimrc"
       file vimrc utente: "$HOME/.vimrc"
    II file vimrc utente: "~/.vim/vimrc"
        file exrc utente: "$HOME/.exrc"
        file dei default: "$VIMRUNTIME/defaults.vim"
         $VIM di riserva: "/usr/local/share/vim"
Compilazione: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Link: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.14 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.6
```

If I try to debug my app with a simple `node inspect test.js` everything is working fine.
Am I missing something or there's something I can do?

**Comment by jayli** [comment]
These errors are all fixed. Please update this plugin and try again.

**Comment by Edo78** [comment]
Thank you, now everything is working.
